"""Initial migration.

Revision ID: f8a52655afe9
Revises:
Create Date: 2025-09-28 05:21:06.039098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a52655afe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cust_type', sa.String(length=50), nullable=False),
    sa.Column('phone_no', sa.String(length=10), nullable=False),
    sa.Column('next_meeting', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SALESMAN', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('payment_mode', sa.String(length=10), nullable=True),
    sa.Column('value', sa.String(length=10), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sales_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('user')
    op.drop_table('lead')
    # ### end Alembic commands ###
